import { Pages } from "enums.slint";
import { SlSettings } from "structs.slint";

export global App {
    in-out property <Pages> page;
    in-out property <string> title:
        page == Pages.Home ? "Home - YetaLauncher" :
        page == Pages.Create ? "Create - YetaLauncher" :
        page == Pages.Accounts ? "Accounts - YetaLauncher" :
        page == Pages.Settings ? "Settings - YetaLauncher" :
        "YetaLauncher";
}

export global Settings {
    in-out property <SlSettings> settings;

    callback update-instance-path();
    callback update-icon-path();
}

export global Palette {
    out property <color> text: #eee;
    out property <color> primary: #ad21db;
    out property <color> bg-primary: #060606;
    out property <color> bg-secondary: #111214;
    out property <color> bg-tertiary: #171718;
}

