import { Pages } from "enums.slint";
import { SlSettings, SlMCVersionDetails, SlSimpleInstance, SlAccounts, SlMCAccount } from "structs.slint";

export global App {
    in-out property <Pages> page;
    in-out property <string> title:
        page == Pages.Home ? "Home - YetaLauncher" :
        page == Pages.Create ? "Create - YetaLauncher" :
        page == Pages.Accounts ? "Accounts - YetaLauncher" :
        page == Pages.Settings ? "Settings - YetaLauncher" :
        "YetaLauncher";
}

export global Settings {
    in-out property <SlSettings> settings;
    in-out property <[SlMCVersionDetails]> version_list;
    in-out property <[SlSimpleInstance]> instances;
    in-out property <SlAccounts> accounts;

    callback update-instance-path();
    callback update-icon-path();
    callback add-java-setting();
    callback save-settings();
    callback update-java-path() -> [string];
    callback test-java(string, string) -> [string];

    callback get-mc-versions();
    callback get-instances(bool);
    pure callback grid-instances(length, [SlSimpleInstance]) -> [[SlSimpleInstance]];
    callback launch-instance(int);

    callback get-accounts();
    pure callback grid-accounts(length, [SlMCAccount]) -> [[SlMCAccount]];
    callback set-selected-account(int);
    callback remove-account(int);
    callback add-account();
}

export global Palette {
    out property <color> text: #eee;
    out property <color> primary: #931ed6;
    out property <color> bg-primary: #060606;
    out property <color> bg-secondary: #131416;
    out property <color> bg-tertiary: #202021;
}

