import { VerticalBox } from "std-widgets.slint";
import { SidebarButton } from "sidebar_button.slint";
export component Sidebar inherits Rectangle {
    property <bool> expanded <=> area.has-hover;
    
    background: #111214;
    border-color: #171718;
    border-width: 1px;
    width: expanded ? 150px : 52px;

    area := TouchArea {
        VerticalLayout {
            SidebarButton { text: "Home"; icon: @image-url("../resources/tabler-icons/home.svg"); expanded: expanded;}
            SidebarButton { text: "Create"; icon: @image-url("../resources/tabler-icons/plus.svg"); expanded: expanded;}
            SidebarButton { text: "Accounts"; icon: @image-url("../resources/tabler-icons/user.svg"); expanded: expanded;}
            SidebarButton { text: "Settings"; icon: @image-url("../resources/tabler-icons/settings.svg"); expanded: expanded;}

            height: parent.height;
            y: parent.y;
        }
        y: 6px;
        height: 182px;
    }

    animate width {
        duration: 150ms;
        easing: ease-in-out;
    }
}