import { SlInstanceType } from "enums.slint";

export struct SlMCVersionDetails {
    id: string,
    typ: string,
    release_time: string
}

export struct SlJavaDetails {
    path: string,
    label: string,
    version: string,
    minecraft_versions: { min: [SlMCVersionDetails], min_set: bool, max: [SlMCVersionDetails], max_set: bool },
    xmx: int,
    xms: int,
    args: string
}

export struct SlSettings {
    instance_size: int,
    instance_path: [string],
    instance_path_set: bool,
    icon_path: [string],
    icon_path_set: bool,
    java_settings: [SlJavaDetails]
}

export struct SlSimpleInstance {
    name: string,
    icon_path: image,
    minecraft_path: string,
    instance_path: string,
    id: int,
    mc_version: string,
    modloader: string,
    last_played: [string],
    instance_type: SlInstanceType
}

export struct SlMCSkin {
    state: string,
    url: string,
    variant: string,
    alias: [string]
}

export struct SlMCAccount {
    username: string,
    uuid: string,
    index: int,
    skins: [SlMCSkin],
    capes: [{id: string}]
}

export struct SlAccounts {
    selected_index: [int],
    accounts: [SlMCAccount]
}