import { HorizontalBox } from "std-widgets.slint";
import { Sidebar } from "widgets/sidebar.slint";
import { Pages } from "enums.slint";
import { App, Settings, Palette } from "globals.slint";
import { SettingsPage } from "pages/settings.slint";
import { HomePage } from "pages/home.slint";
import { AccountsPage } from "pages/accounts.slint";
import { CreatePage } from "pages/create.slint";
import { NotifContainer } from "widgets/notif_container.slint";

import "../resources/fonts/Nunito-Medium.ttf";
import { InstancePage } from "pages/instance.slint";

export component MainWindow inherits Window {
    in-out property <Pages> page <=> App.page;

    title <=> App.title;
    background: Palette.bg-primary;
    padding: 0;
    default-font-family: "Nunito";
    default-font-size: 16px;
    default-font-weight: 500;

    Sidebar { x: 0px; z: 5; }
    Rectangle {
        z: 0;
        x: 52px;
        width: parent.width - 52px;

        if page == Pages.Home: HomePage {}
        if page == Pages.Create: CreatePage {}
        if page == Pages.Accounts: AccountsPage {}
        if page == Pages.Settings: SettingsPage {}
        if page == Pages.Instance: InstancePage {}
    }
    NotifContainer { z: 50; parent_height: root.height; }
}

export { App, Settings }