import { SlSimpleInstance } from "../structs.slint";
import { App, Palette, Instances } from "../globals.slint";
import { Pages } from "../enums.slint";

export component InstanceTile inherits VerticalLayout {
    padding: 4px;
    in-out property <SlSimpleInstance> instance;
    private property <bool> hovering: area.has-hover || launch-area.has-hover;

    container := Rectangle {
        clip: true;
        border-radius: 6px;
        border-color: hovering ? Palette.primary : Palette.bg-secondary;
        border-width: 1px;
        background: Palette.bg-secondary;
        height: icon.height + 54px;
    
        icon := Rectangle {
            x: 6px; y: 6px;
            width: parent.width - 2 * self.x;
            height: self.width;
            border-radius: container.border-radius;
            background: Palette.bg-tertiary;
            clip: true;

            Image {
                width: parent.width;
                height: parent.height;
                source: instance.icon-path;
            }
        }

        Text {
            x: 4px; y: icon.height + 8px;
            width: parent.width - 2 * self.x;
            font-size: 20px;
            overflow: elide;
            color: Palette.text;
            text: instance.name;
        }

        Text {
            x: 4px; y: icon.height + 32px;
            width: parent.width - 2 * self.x;
            font-size: 14px;
            color: Palette.text;
            text: instance.mc-version + ", " + instance.modloader;
        }

        Rectangle {
            background: launch-area.has-hover ? Palette.primary : Palette.primary.transparentize(0.3);
            y: parent.height - self.height;
            clip: true;
            height: hovering ? 30px : 0px;

            HorizontalLayout {
                x: (parent.width - self.width) / 2;
                width: self.min-width;
                spacing: 2px;
                padding: 3px;

                Image {
                    source: @image-url("../../resources/tabler-icons/player-play.svg");
                    height: 24px;
                    width: 24px;
                    colorize: Palette.text;
                }

                Text {
                    text: "Play";
                    color: Palette.text;
                    font-weight: 700;
                    font-size: 18px;
                }
            }

            launch_area := TouchArea {
                z: 5;
                mouse-cursor: pointer;
                clicked => {
                    Instances.launch-instance(instance.id)
                }
            }

            animate background {
                duration: 150ms;
            }

            animate height {
                duration: 100ms;
                easing: ease-in-out;
            }
        }

        area := TouchArea {
            mouse-cursor: pointer;
            z: -1;

            clicked => {
                App.current-instance = instance;
                App.page = Pages.Instance
            }
        }

        animate border-color {
            duration: 150ms;
        }
    }
}