import { Button, HorizontalBox } from "std-widgets.slint";
import { Pages } from "../enums.slint";
import { App, Palette } from "../globals.slint";

export component SidebarButton inherits VerticalLayout {
    in property <string> text;
    in property <Pages> page;
    in property <image> icon;
    in property <bool> expanded;

    padding-left: 4px;
    padding-right: 4px;

    Rectangle { // Has to be a separate element because there's no margin property 
        background: area.has-hover ? Palette.primary : Palette.bg-secondary;
        height: 47px;
        border-radius: 6px;
        clip: true;

        area := TouchArea {
            mouse-cursor: pointer;
            clicked => { App.page = page }
        }
        HorizontalBox {
            Image {
                y: -2px;
                source: icon;
                width: 32px;
                height: 32px;
                colorize: Palette.text;
            }
            if expanded: Text {
                text: text;
                color: Palette.text;
                font-weight: 600;
                font-size: 20px;
            }
        }
    
        animate background {
            duration: 100ms;
        }
    }

}