import { VerticalBox } from "std-widgets.slint";
import { SidebarButton } from "sidebar_button.slint";
import { Pages } from "../enums.slint";
import { Palette } from "../globals.slint";

export component Sidebar inherits Rectangle {
    property <bool> expanded <=> area.has-hover;
    
    background: Palette.bg-secondary;
    border-color: Palette.bg-tertiary;
    border-width: 1px;
    width: expanded ? 150px : 52px;

    area := TouchArea {
        layout := VerticalLayout {
            SidebarButton { text: "Home"; page: Pages.Home; icon: @image-url("../../resources/tabler-icons/home.svg"); expanded: expanded;}
            SidebarButton { text: "Create"; page: Pages.Create; icon: @image-url("../../resources/tabler-icons/plus.svg"); expanded: expanded;}
            SidebarButton { text: "Accounts"; page: Pages.Accounts; icon: @image-url("../../resources/tabler-icons/user.svg"); expanded: expanded;}
            SidebarButton { text: "Settings"; page: Pages.Settings; icon: @image-url("../../resources/tabler-icons/settings.svg"); expanded: expanded;}

            y: parent.y;
        }
        y: 6px;
        height: 198px;
    }

    animate width {
        duration: 150ms;
        easing: ease-in-out;
    }
}