import { App, Settings, Accounts } from "../globals.slint";
import { ListView } from "std-widgets.slint";
import { AccountTile } from "../widgets/account_tile.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { SlSimpleInstance } from "../structs.slint";
import { Topbar } from "../widgets/topbar.slint";

export component AccountsPage inherits VerticalLayout {
    Topbar {
        text: "Accounts";

        IconButton {
            y: 3px; x: root.width - 249px;
            icon: @image-url("../../resources/tabler-icons/plus.svg");
            text: "Add Account";
    
            clicked => { Accounts.add-account(); }
        }
    }

    if Accounts.accounts.accounts.length > 0: view := ListView {
        for accounts_row in Accounts.grid-accounts(view.visible-width, Accounts.accounts.accounts): HorizontalLayout {
            for account in accounts-row: AccountTile {
                width: view.visible-width / ceil(view.visible-width / ((30 - Settings.settings.instance_size) * 15px));
                account: account;
            }
        }
    }

    HorizontalLayout {
        init => {
            if Accounts.accounts.accounts.length == 0 {
                Accounts.get-accounts();
            }
        }
    }
}