import { App, Settings } from "../globals.slint";
import { ListView } from "std-widgets.slint";
import { InstanceTile } from "../widgets/instance_tile.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { SlSimpleInstance } from "../structs.slint";
import { Topbar } from "../widgets/topbar.slint";
import { CustomSlider } from "../widgets/custom_slider.slint";

export component HomePage inherits VerticalLayout {
    Topbar {
        text: "Instances";

        Text {
            x: 3px; y: 13px;
            font-weight: 500;
            font-size: 16px;
            text: "(" + Settings.instances.length + ")";
        }

        IconButton {
            x: self.width - 47px; y: 3px;
            icon: @image-url("../../resources/tabler-icons/refresh.svg");
            
            clicked => {
                if !Settings.is-loading-instances {
                    Settings.get-instances(true);
                    Settings.is-loading-instances = true;
                }
            }
        }

        CustomSlider {
            y: 19px; x: parent.width - 275px;
            width: 120px;
            range: { min: 8, max: 24};
            value: Settings.settings.instance-size;
            
            edited(val) => { Settings.update-instance-size(val); }
        }
    }

    if Settings.instances.length > 0: view := ListView {
        for instance_row in Settings.grid-instances(view.visible-width, Settings.instances, Settings.settings.instance-size): HorizontalLayout {
            for instance in instance-row: InstanceTile {
                width: view.visible-width / ceil(view.visible-width / ((30 - Settings.settings.instance_size) * 15px));
                instance: instance;
            }
        }
    }

    HorizontalLayout {
        init => {
            if Settings.instances.length == 0 && !Settings.is-loading-instances {
                Settings.get-instances(false);
                Settings.is-loading-instances = true;
            }
        }
    }
}