import { App, Settings } from "../globals.slint";
import { ListView } from "std-widgets.slint";
import { InstanceTile } from "../widgets/instance_tile.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { SlSimpleInstance } from "../structs.slint";

export component HomePage inherits VerticalLayout {

    IconButton {
        text: "Refresh";
        
        clicked => {
            Settings.get-instances(true);
        }
    }

    if Settings.instances.length > 0: view := ListView {
        for instance_row in Settings.grid-instances(view.visible-width, Settings.instances): HorizontalLayout {
            for instance in instance-row: InstanceTile {
                width: view.visible-width / ceil(view.visible-width / ((30 - Settings.settings.instance_size) * 15px));
                instance: instance;
            }
        }
    }

    HorizontalLayout {
        init => {
            if Settings.instances.length == 0 {
                Settings.get-instances(false);
            }
        }
    }
}