import { SlSimpleInstance } from "../structs.slint";
import { App, Instances, Palette, CurrentInstance } from "../globals.slint";
import { Topbar } from "../widgets/topbar.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { TabWidget } from "std-widgets.slint";
import { ModsTab } from "instance_tabs/mods.slint";


export component InstancePage inherits VerticalLayout {
    private property instance <=> CurrentInstance.current-simple;

    Topbar {
        text: instance.name;

        IconButton {
            y: 3px; x: self.width - 108px;
            text: "Launch";

            icon: @image-url("../../resources/tabler-icons/caret-right.svg");

            clicked => {
                Instances.launch-instance(instance.id);
            }
        }
    }

    content := VerticalLayout {
        padding: 10px;
        spacing: 10px;

        Rectangle {
            border-radius: 8px;
            background: Palette.bg-secondary;
            height: 200px;
            border-width: 1px;
            border-color: Palette.bg-tertiary;

            image := Image {
                x: 8px; y: 8px;
                height: parent.height - self.y * 2;
                source: instance.icon;
            }

            VerticalLayout {
                x: image.width + image.x * 2; y: 8px;

                Text {
                    private property <string> last-played: instance.last-played.length == 1 ? instance.last-played[0] : "Never";
                    text: "Last played: " + last-played;
                }
                Text {
                    private property <string> last-played-for: instance.last-played-for.length == 1 ? instance.last-played-for[0] : "Unknown";
                    text: "Last played for: " + last-played-for;
                }
                Text {
                    private property <string> total-time-played: instance.total-time-played.length == 1 ? instance.total-time-played[0] : "Unknown";
                    text: "Total time played: " + total-time-played;
                }
                Text {
                    private property <string> play-count: instance.play-count.length == 1 ? instance.play-count[0] : "Unknown";
                    text: "Number of times played: " + play-count;
                }
            }
        }

        Rectangle {
            border-radius: 8px;
            background: Palette.bg-secondary;
            border-width: 1px;
            border-color: Palette.bg-tertiary;

            Rectangle {
                background: Palette.bg-tertiary;
                y: 31px;
                z: 5;
                height: 2px;
            }

            TabWidget {
                y: 1px;

                Tab {
                    title: "Mods";
                    ModsTab {}
                }
                Tab {
                    title: "Mods 2";
                    Text { text: "test 2"; }
                }
            }
        }
    }
}