import { Settings, Palette } from "../globals.slint";
import { VerticalBox } from "std-widgets.slint";
import { SettingsContainer } from "../widgets/settings_container.slint";


export component SettingsPage inherits VerticalLayout {
    padding: 8px;

    SettingsContainer {
        header: "Instance Path";
        text: Settings.settings.instance-path-set ? Settings.settings.instance-path[0] : "Click to set!";
        clicked => { Settings.update-instance-path(); }
    }
}