name: 'build-dev'
on:
  push:

jobs:
  release:
    name: build-dev ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          - name: windows-x86_64
            container: windows-latest
            target: x86_64-pc-windows-msvc
            args: "--no-default-features --features use-skia"

          - name: macOS-x86_64
            container: macOS-latest
            target: x86_64-apple-darwin
            args: "--no-default-features --features use-skia"

          - name: macOS-aarch64
            container: macOS-latest
            target: aarch64-apple-darwin
            args: "--no-default-features --features use-skia"
          
          - name: linux-x86_84-qt
            container: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            args: ""

          - name: linux-x86_84-skia
            container: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            args: "--no-default-features --features use-skia"

    runs-on: ${{ matrix.platform.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
        if: ${{ !contains(matrix.platform.args, 'no-default-features') }}

      - name: Setup mold as the linker
        uses: rui314/setup-mold@main
        if: contains(matrix.platform.target, 'linux')

      - name: Setup Rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Build the binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release ${{ matrix.platform.args }}"  # Build with the release profile and enable the backends to use for the platform
          strip: false

      - name: Mark binary as executable
        run: chmod +x target/${{ matrix.platform.target }}/release/yetalauncher
        if: contains(matrix.platform.target, 'linux')

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: yetalauncher-${{ matrix.platform.name }}
            path: |
              target/${{ matrix.platform.target }}/release/yetalauncher
              target/${{ matrix.platform.target }}/release/yetalauncher.exe